title: Yingtong (Angel) Zhong # your name (or website title) here
logo: "/images/profile_picture.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Social Policy and Data Analytics, with Certificate in GIS and Spatial Analysis at University of Pennsylvania
  <br><br>
  As an aspiring data seeker, I’m interested in data science in a broad area and specialized in politics and policy, tech, and social goods. 
  <br>
  I am experienced in data analytics, spatial analysis and visualization.I uncover valuable insights through my projects using Python, R and ArcGIS. My other skillsets include but not limit to Python, SQL, R, ArcGIS, Tableau, AWS and A/B testing.
  <br><br>
  <a href="https://www.linkedin.com/in/yingtongzhong">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/Yingtong-Z/Yingtong-Z.github.io/blob/b5507f2e024b217ea4d9b7f6a7cc1cca1879321a/pdf/Yingtong%20Zhong%20-%20CV.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
