title: Yingtong (Angel) Zhong # your name (or website title) here
logo: "/images/profile_picture.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  🎓 Master of Social Policy and Data Analytics, with Certificate in GIS and Spatial Analysis at University of Pennsylvania
  💼 Currently an Analyst at Econsult Solutions
  <br><br>
  As an aspiring data-driven problem solver, I specialize in data analytics, spatial analysis, and applying LLMs + automation to uncover insights and streamline workflows. My projects blend Python, R, SQL, and ArcGIS to transform complex datasets into actionable outcomes. I’m especially interested in leveraging data to drive impact in public policy, technology, and social innovation.
  <br><br>
  <a href="https://www.linkedin.com/in/yingtongzhong">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/Yingtong-Z/Yingtong-Z.github.io/blob/b5507f2e024b217ea4d9b7f6a7cc1cca1879321a/pdf/Yingtong%20Zhong%20-%20CV.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
